### ISSUE TITLE
Back-To-Top

### ISSUE THREAD

**Issue by danielang** [t3framework/purity_iii#6]
Is the page height less than the screen height the Back-To-Top-Button looks pretty awful. It is displayed above the footer:

![purity_iii_issue](https://f.cloud.github.com/assets/6752808/2403499/aeb8e940-aa2f-11e3-8387-f62f5e78efbe.PNG)

 You can solve this, when you add under "#back-to-top" in the style.less-file:

&.affix-top {
    visibility: hidden;
  }

**Comment by joomlart** [comment]
Merge your commit
